//
//  SChartCategoryAxis.h
//  SChart
//
//  Copyright 2011 Scott Logic Ltd. All rights reserved.
//

#import <Foundation/Foundation.h>

@class SChartNumberRange;
@class SChartDataSeries;

/** 
 A SChartCategoryAxis is a subclass of SChartAxis designed to work with discrete data points with no linear correlation between values.
 For the purposes of ranges, each data point value for a category axis is represented by an index (generated by the order in which data points are added to the series - but removing duplicates). This determines order and can be used to set ranges.
 */
@interface SChartCategoryAxis : SChartAxis {
    NSMutableArray *categories;
    BOOL categoriesSet;
}



#pragma mark - 
#pragma mark Initialisation
/** @name Initialisation */
/** Init with a number range representing the indices.
 
 The range is based upon the index number of each category. The index number of a category can be found from the array `categories` - which contains the actual set of categories. */
- (id)initWithRange:(SChartNumberRange *)range;

#pragma mark -
#pragma mark Categories
/** @name Categories on this axis */
/** An array containing all of the categories across all series linked to this axis.
 
 Any duplicates will be removed, therefore the `dataIndex` from the data source may not correspond to the index of the category*/
@property (nonatomic, retain) NSMutableArray *categories;

#pragma mark -
#pragma mark Internal: Categories
@property (nonatomic) BOOL categoriesSet;

// Assign all data to categories.
- (void)setupCategories;

// Assign a datapoint to a category.
- (SChartDataSeries *)categorize:(SChartDataSeries *)ds;

@end
