#ifndef SC_PATH_TO_ALL_PLUGINS_JAVASCRIPT_EXPORT_INCLUDED_H
#define SC_PATH_TO_ALL_PLUGINS_JAVASCRIPT_EXPORT_INCLUDED_H

@class NSString, NSArray;

NSArray* scWebPluginsClasses( void );
NSString* pathToAllPluginsJavascripts( void );

#endif //SC_PATH_TO_ALL_PLUGINS_JAVASCRIPT_EXPORT_INCLUDED_H
