#ifndef SC_WEBPLUGINS_JAVASCRIPT_EXPORT_INCLUDED_H
#define SC_WEBPLUGINS_JAVASCRIPT_EXPORT_INCLUDED_H

@class NSString;
NSString* scWebPluginsCoreJavascript( void );

#endif //SC_WEBPLUGINS_JAVASCRIPT_EXPORT_INCLUDED_H
